#!/usr/bin/env python3
import sys
from number_place import readfile, solve, display_grid

def main(filename):
    grid, clues = readfile(filename)
    print('puzzle')
    display_grid(grid)
    grid = solve(grid, clues)
    print('solution')
    display_grid(grid)

if __name__ == '__main__':
    if len(sys.argv) < 2:
        sys.stderr.write('Usage: %s filename\n' % sys.argv[0])
        sys.exit(1)
    try:
        main(sys.argv[1])
    except Exception as error:
        sys.stderr.write('%s\n' % error)
        sys.exit(1)
